# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/

load("rules.bzl", "fortran_binary")

fortran_binary(
    name = "disconnection",
    file = "disconnectionDPS.f90",
    toolchain = "toolchains//:fortran",
    o_name = "disconnection",
    test = "test.json"
)

fortran_binary(
    name = "rancoords",
    file = "rancoords.f",
    toolchain = "toolchains//:fortran",
    o_name = "rancoords",
    test = "test.json"
)